# Generated by Django 6.0.4 on 2026-05-29 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('kana', models.CharField(blank=True, max_length=100, verbose_name='フリガナ')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='性別')),
                ('nearest_station', models.CharField(blank=True, max_length=100, verbose_name='最寄駅')),
                ('education', models.CharField(blank=True, max_length=255, verbose_name='最終学歴')),
                ('qualification', models.TextField(blank=True, verbose_name='資格')),
                ('self_pr', models.TextField(blank=True, verbose_name='自己PR')),
                ('skill_summary', models.TextField(blank=True, verbose_name='スキル概要')),
                ('career_summary', models.TextField(blank=True, verbose_name='経歴概要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='No.')),
                ('project_name', models.CharField(blank=True, max_length=255, verbose_name='案件名・業務名')),
                ('work_detail', models.TextField(blank=True, verbose_name='作業内容')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='役割')),
                ('phase', models.CharField(blank=True, max_length=255, verbose_name='工程')),
                ('os', models.CharField(blank=True, max_length=255, verbose_name='OS')),
                ('language', models.CharField(blank=True, max_length=255, verbose_name='言語')),
                ('database', models.CharField(blank=True, max_length=255, verbose_name='DB')),
                ('tools', models.CharField(blank=True, max_length=255, verbose_name='ツール')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('skill_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='reports.skillsheet', verbose_name='スキルシート')),
            ],
        ),
    ]
